version: '2'

services:
    front:
      image: nginx:alpine
      container_name: ${APP_NAME}-front
      ports:
        - 443
        - 80
      expose:
        - 443
      links:
        - php
      volumes_from:
        - php
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /etc/letsencrypt/:/etc/letsencrypt/
        - ./var/logs:/var/logs/nginx
      environment:
        VIRTUAL_PROTO: https
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        VIRTUAL_PORT: 443
        LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    php:
      build: docker/php
      container_name: ${APP_NAME}-php
      ports:
        - 9000:9000
      volumes:
        - ./:/var/www/html

networks:
    default:
        external:
          name: ${NGINX_PROXY_NETWORK}
